apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3www.fullname" . }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "s3www.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "s3www.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: S3_ENDPOINT
              value: {{ .Values.s3.endpoint }}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "s3www.fullname" . }}
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "s3www.fullname" . }}
                  key: secret-key
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - "-endpoint=$(S3_ENDPOINT)"
            - "-accessKey=$(S3_ACCESS_KEY)"
            - "-secretKey=$(S3_SECRET_KEY)"
            - "-bucket=$(S3_BUCKET)"
            - "-address=0.0.0.0:8080"
